# ============== Stage 1 ================
FROM node:alpine AS development

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY tsconfig.json tsconfig.json
COPY nest-cli.json nest-cli.json

COPY apps/bot apps/bot
COPY libs libs

RUN pnpm install -r --frozen-lockfile

RUN pnpm run build bot
